version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reddit-classifier-api
    ports:
      - "8080:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 2G
