[project]
name = "reddit-post-classifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.10"
dependencies = [
    "torch==2.8.0",
    "transformers>=4.28.0",
    "pandas>=1.5.0",
    "scikit-learn>=1.0.0",
    "wandb>=0.19.9",
]
