[project]
name = "reddit-post-classifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "torch>=2.0.0",
    "transformers>=4.28.0",
    "pandas>=1.5.0",
    "scikit-learn>=1.0.0",
]
